#!/bin/bash

echo "🚀 SaaS AI Inspection Platform - Access URLs"
echo "============================================"
echo ""
echo "🌐 Main Application:"
echo "   • Homepage: https://filament-starter.test"
echo "   • Admin Panel: https://filament-starter.test/admin"
echo ""
echo "🏢 Demo Tenant:"
echo "   • Homepage: https://demo1754460803.test"
echo "   • Admin Panel: https://demo1754460803.test/admin"
echo "   • Login: demo@demo.test / password"
echo ""
echo "👨‍💼 Super Admin:"
echo "   • Login: rv.singh462@gmail.com / [your password]"
echo ""
echo "🔧 Development Tools:"
echo "   • Horizon: https://filament-starter.test/horizon"
echo "   • Health Check: https://filament-starter.test/health"
echo ""
echo "💡 Useful Commands:"
echo "   • php artisan tenants:list"
echo "   • php artisan queue:work"
echo "   • valet links"
echo "   • ./reset-db.sh"
echo ""
echo "🚗 Valet Commands:"
echo "   • valet links           # List all links"
echo "   • valet secure [name]   # Enable SSL"
echo "   • valet unsecure [name] # Disable SSL"
echo ""
